DROP DATABASE IF EXISTS products;

CREATE DATABASE products;

\c products;

CREATE TABLE IF NOT EXISTS products
(
    id integer NOT NULL GENERATED BY DEFAULT AS PRIMARY KEY,
    name character varying(30) NOT NULL,
    slogan character varying(200) NOT NULL,
    description character varying(1000) NOT NULL,
    category character varying(60) NOT NULL,
    default_price numeric NOT NULL,
)

CREATE TABLE IF NOT EXISTS styles
(
    id integer NOT NULL GENERATED BY DEFAULT AS PRIMARY KEY,
    productId integer NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    name character varying(60)  NOT NULL,
    default_style boolean NOT NULL,
    original_price character varying(10) NOT NULL,
    sale_price character varying(10) DEFAULT NULL::character varying,
)

CREATE TABLE IF NOT EXISTS skus
(
    id integer NOT NULL GENERATED BY DEFAULT AS PRIMARY KEY,
    styleId integer NOT NULL REFERENCES styles (id) ON DELETE CASCADE,
    size character varying(8) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
)

CREATE TABLE IF NOT EXISTS photos
(
    id integer NOT NULL GENERATED BY DEFAULT AS PRIMARY KEY,
    styleId integer NOT NULL REFERENCES styles (id) ON DELETE CASCADE,
    url text NOT NULL,
    thumbnail_url text NOT NULL,
)

CREATE TABLE IF NOT EXISTS features
(
    id integer NOT NULL GENERATED BY DEFAULT AS PRIMARY KEY,
    product_id integer NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    feature character varying(30) NOT NULL,
    value character varying(100) NOT NULL,
)

CREATE TABLE IF NOT EXISTS related
(
    id integer NOT NULL GENERATED BY DEFAULT AS PRIMARY KEY,
    current_product_id integer NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    related_product_id integer NOT NULL,
)
