DROP DATABASE IF EXISTS products;

CREATE DATABASE products;

\c products;

CREATE TABLE IF NOT EXISTS products
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(30) NOT NULL,
    slogan character varying(200) NOT NULL,
    description character varying(1000) NOT NULL,
    category character varying(60) NOT NULL,
    default_price character varying(20)
);

CREATE TABLE IF NOT EXISTS styles
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productId integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    name character varying(60)  NOT NULL,
    sale_price character varying(20),
    original_price character varying(10) NOT NULL,
    default_style bit NOT NULL
);

CREATE TABLE IF NOT EXISTS skus
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    styleId integer NOT NULL REFERENCES styles (id) ON DELETE CASCADE,
    size character varying(8) NOT NULL,
    quantity integer NOT NULL
);

CREATE TABLE IF NOT EXISTS photos
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    styleId integer NOT NULL REFERENCES styles (id) ON DELETE CASCADE,
    url text NOT NULL,
    thumbnail_url text NOT NULL
);

CREATE TABLE IF NOT EXISTS features
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    feature character varying(30) NOT NULL,
    value character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS related
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_product_id integer NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    related_product_id integer NOT NULL
);

COPY products (id, name, slogan, description, category, default_price)
FROM '/mnt/c/Users/Kenny/Desktop/SDC Data/product.csv'
DELIMITER ','
CSV HEADER;

COPY styles (id, productId, name, sale_price, original_price, default_style)
FROM '/mnt/c/Users/Kenny/Desktop/SDC Data/styles.csv'
DELIMITER ','
CSV HEADER;

COPY skus (id, styleId, size, quantity)
FROM '/mnt/c/Users/Kenny/Desktop/SDC Data/skus.csv'
DELIMITER ','
CSV HEADER;

COPY photos (id, styleId, url, thumbnail_url)
FROM '/mnt/c/Users/Kenny/Desktop/SDC Data/photos.csv'
DELIMITER ','
CSV HEADER;

COPY features (id, product_id, feature, value)
FROM '/mnt/c/Users/Kenny/Desktop/SDC Data/features.csv'
DELIMITER ','
CSV HEADER;

COPY related (id, current_product_id, related_product_id)
FROM '/mnt/c/Users/Kenny/Desktop/SDC Data/related.csv'
DELIMITER ','
CSV HEADER;

CREATE INDEX prod_id_idx ON products (id);
CREATE INDEX sty_prod_id_idx ON styles (productId);
CREATE INDEX skus_sty_id_idx ON skus (styleId);
CREATE INDEX phot_sty_id_idx ON photos (styleId);
CREATE INDEX feat_prod_id_idx ON features (product_id);
CREATE INDEX rel_curr_prod_id_idx ON related (current_product_id);